### ISSUE TITLE
Script errors out when running it consecutive times: ERROR: Bucket already exists

### ISSUE THREAD

**Issue by gleeke** [invictus-ir/Invictus-AWS#2]
I run the script once, then when I want to run it again for a different region I get the following:

```
Logs bucket does not exists, creating it now: invictus-aws-2022-09-21-4j75d
ERROR: Bucket already exists
```

Perhaps you could add the option to specify a bucket as an argument? 

However, the random_chars at the end of the bucket name are different each time I run the script. So the bucket it tries to create does not already exist.

**Comment by invictus-ir** [comment]
Hi there, I explained this in the other issue you have created. But on line 11 and 12 of the script you can hardcode bucket names. 
I'd have to test to see if I can replicate the error if I run it in different regions.

**Comment by invictus-ir** [comment]
Error is fixed.
