### ISSUE TITLE
Add a timeframe to queries

### ISSUE THREAD

**Issue by awsrossw** [invictus-ir/Invictus-AWS#5]
Adding a timeframe to Athena queries will help the operator scope their investigation.

<Note> - I was able to add this functionality, by walking down the code and adding "timeframe" to function calls.

   parser.add_argument(
        "-x",
        "--timeframe",
        type=str,
        help="[+] Time Frame, in days, to perform analysis step. if input is 7, analysis step will search the last 7 days."
    )

and using the supplied logic to edit the queries in the file.

#replacing DATABASE and TABLE in each query
            value = value.replace("DATABASE", db)
            value = value.replace("TABLE", table)
            value = value.replace("TIMEFRAME",timeframe)
            print(f"[+] Running Query : {key}")

**Comment by benjamin-glz** [comment]
In the way I see it, if this feature is set up, users won't be able to not use it if they need/want.
I think it's better to show in the documentation what the user can add to the queries if he wants to scope his queries. But there is no real need to set it up in the tool. 
But if you find a good solution which can satisfy everyone, fell free to suggest a pull request !

**Comment by awsrossw** [comment]
I understand. Timeframe could be optional parameter, but with documentation on how to change the queries to utilize the date. Athena queries will timeout after a period of time if you are not time bounding the query.

This currently works for me, but I quickly just added parts to your code to pass the parameter.



 I re-wrote the out of the box queries to use the "eventDay" partition and added 
"value = value.replace("TIMEFRAME",timeframe)" to your code.

aws_attached_malicious_lambda_layer: SELECT * FROM DATABASE.TABLE WHERE (api.service.name = 'lambda.amazonaws.com' AND api.operation LIKE 'UpdateFunctionConfiguration%' ESCAPE '\') AND eventDay > cast(date_format(current_timestamp - INTERVAL 'TIMEFRAME' day, '%Y%m%d%H') as varchar)

aws_cloudtrail_disable_logging: SELECT * FROM DATABASE.TABLE WHERE (api.service.name = 'cloudtrail.amazonaws.com' AND api.operation IN ('StopLogging', 'UpdateTrail', 'DeleteTrail')) AND eventDay > cast(date_format(current_timestamp - INTERVAL 'TIMEFRAME' day, '%Y%m%d%H') as varchar)

aws_config_disable_recording: SELECT * FROM DATABASE.TABLE WHERE (api.service.name = 'config.amazonaws.com' AND api.operation IN ('DeleteDeliveryChannel', 'StopConfigurationRecorder')) AND eventDay > cast(date_format(current_timestamp - INTERVAL 'TIMEFRAME' day, '%Y%m%d%H') as varchar)

**Comment by benjamin-glz** [comment]
Alright I'll try to do something like that. But instead of being only able to select the last x days, I'll try to do x<logs<y so that the user can select for example 3 days that were last month. I feel it's way less restrictive.
Thank you for your time !

**Comment by awsrossw** [comment]
👍 - if you look at my examples

 eventDay > cast(date_format(current_timestamp - INTERVAL 'TIMEFRAME' day, '%Y%m%d%H') as varchar)

and i have 7 as the TIMEFRAME - this is going to be the last 7 days, this is a typical query that a SOC team will do looking evidence. 

I can help workout the docs/readme. Since the examples Im giving you are OCSF and Security Lake Specific.

**Comment by benjamin-glz** [comment]
Feature added. Just modified the timeframe sequence in the query but it should work the same. Will be available by the end of the month on the main branch.
Thank you for the proposal !
