### ISSUE TITLE
Add command line option to load different query files

### ISSUE THREAD

**Issue by awsrossw** [invictus-ir/Invictus-AWS#6]
Pull out the static definition of the queries.yaml (leave as the default for ease of use) and make it a command line option

    parser.add_argument(
        "-f",
        "--queryfile",
        type=str,
        help="[+]  File containing queries that you want Invictus-aws to run."
    )

        try:
            with open('source/files/queries.yaml') as f:
                queries = yaml.safe_load(f)
        except Exception as e:
            print(f"[!] Error : {str(e)}")

**Comment by benjamin-glz** [comment]
Feature added, will be available by the end of the month on the main branch.
Thank you for the proposal !
