### ISSUE TITLE
problem with the function 'verify_all_regions'

### ISSUE THREAD

**Issue by Anny212** [invictus-ir/Invictus-AWS#8]
Hi,

I am attempting to run this tool on a Windows 10 computer. I have installed AWS CLI and Python (version aws-cli/1.32.59 Python/3.8.2 Windows/10 botocore/1.34.59). Additionally, I have configured the AWS CLI with my AWS account and, of course, installed the requirements from the requirements.txt file.

However, when I execute the tool with the command main.py -A -w local, I encounter the following error:

 line 208, in verify_all_regions
    regions = response["Regions"]
KeyError: 'Regions'

![invictus error](https://github.com/invictus-ir/Invictus-AWS/assets/162898152/651885e5-a949-4df8-a1ba-a251e3faf428)

I should note that it works well on my Windows 11 system. I've tried uninstalling and reinstalling Python, AWS CLI, and this Invictus tool, but the issue persists. Could this be a problem specific to Windows 10?

Thanks.

**Comment by invictus-korstiaan** [comment]
Hi thanks for opening this issue. We're not aware of this issue. Just performed some testing and it works on my Mac and on my Win 11 laptop. I don't have a Win10 laptop here to test, I haven't heard from other people if they this issue. 

- Do you have the same user/access configured for both tests on Win10 and Win11?

**Comment by Anny212** [comment]
Hi,
Yes, I have the same permissions as the users.

**Comment by Anny212** [comment]
I did some checks and found that if the system's clock isn't defined correctly, this error is shown. 
So, I think we have a solution!
Thanks

**Comment by invictus-korstiaan** [comment]
Hi Anny, thank you for letting me know. We're a bit busy now so wanted to test it later with a Win10 machine, but if that solved it for you I'll close the issue.
